GdsVideoBackend/Models/CategoryTypeViewModel.cs
namespace GdsVideoBackend.Models
{
    public class CategoryTypeViewModel
    {

        public int CategoryTypeId { get; set; }

        public int CategoryId { get; set; }

        public string CategoryTypeName { get; set; }

        public int? CategoryTypePriceId { get; set; }

        public string FileThumbnail { get; set; }

        public string Content { get; set; }

        public int AgeOrderId { get; set; }

        public int CategoryTypeOrderId { get; set; }

        public int AuthorId { get; set; }
    }
}

GdsVideoBackend/Controllers/CategoryTypeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gds.ServiceModel.BackEndModel;
using Gds.ServiceModel.ControlObject;
using Gds.Setting;
using GdsVideoBackend.Domain;
using GdsVideoBackend.Models;

namespace GdsVideoBackend.Controllers
{
    public class CategoryTypeController : Controller
    {
        private readonly ICategoryTypeService _categoryTypeService;

        public CategoryTypeController(ICategoryTypeService categoryTypeService)
        {
            _categoryTypeService = categoryTypeService;
        }

        //
        // GET: /CategoryType/
        public ActionResult Index(int categoryId)
        {
            var prices = _categoryTypeService.GetPrices().Select(x => new PriceSetting
            {
                Id = x.CategoryTypePriceId,
                Price = x.Price
            }).ToList();

            var ageOrder = _categoryTypeService.GetAgeOrders().Select(x => new AgeOrderSetting
            {
                Id = x.AgeOrderId,
                Name = x.AgeOrderName
            }).ToList();

            var authors = _categoryTypeService.GetAuthors().Select(x => new AuthorSetting
            {
                Id = x.AuthorId,
                Name = x.AuthorName,
            });
            var model = new CategoryTypeFromViewModel
            {
                PriceSetting = new List<PriceSetting>(),
                AgeOrderSetting = new List<AgeOrderSetting>(),
                AuthorSettings = new List<AuthorSetting>()
            };
            model.PriceSetting.AddRange(prices);
            model.AgeOrderSetting.AddRange(ageOrder);
            model.AuthorSettings.AddRange(authors);
            return View(model);
        }

        public JsonResult GetPrices()
        {
            var result = _categoryTypeService.GetPrices().Select(x => new
            {
                Id = x.CategoryTypePriceId,
                x.Price
            });
            return Json(new { isSuccess = false, data = result }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetParent(int categoryId, int pageIndex, int pageSize)
        {
            var result = _categoryTypeService.GetParentCategoryTypes(categoryId, pageIndex, pageSize);
            return result.Result.Any() ? Json(new { isSuccess = true, data = result }, JsonRequestBehavior.AllowGet)
                : Json(new { isSuccess = false, data = new PagingResultModel<CategoryTypesModel>() }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost, ValidateInput(false)]
        public JsonResult Insert()
        {
            var item = GetValueInFrom(Request);
            
            int categoryTypeId;
            var fileName = string.Empty;
            if (Request.Files.AllKeys.Any() && Request.Files[0] != null)
            {
                fileName = Request.Files[0].FileName;
            }
            var result = _categoryTypeService.InsertCategoryType(item, fileName, out categoryTypeId);
            item.CategoryTypeId = categoryTypeId;
            UploadThumbnailImage(item, Request);
            return result ? Json(new { isSuccess = true }) : Json(new { isSuccess = false }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost, ValidateInput(false)]
        public JsonResult Update()
        {
            var item = GetValueInFrom(Request);
            item = UploadThumbnailImage(item, Request);
            var result = _categoryTypeService.UpdateCategoryType(item);
            return result ? Json(new { isSuccess = true }) : Json(new { isSuccess = false }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Delete(int categoryTypeId, string type)
        {
            var result = _categoryTypeService.DeleteCategoryType(categoryTypeId);
            return result ? Json(new { isSuccess = true, type = type }) : Json(new { isSuccess = false }, JsonRequestBehavior.AllowGet);
        }

        private CategoryTypeViewModel GetValueInFrom(HttpRequestBase request)
        {
            var item = new CategoryTypeViewModel();
            item.CategoryId = Convert.ToInt32(request["CategoryId"]);
            item.CategoryTypeId = string.IsNullOrEmpty(request["CategoryTypeId"]) ? 0 : Convert.ToInt32(request["CategoryTypeId"]);
            item.CategoryTypeName = request["CategoryTypeName"];
            item.Content = request["Content"];
            item.CategoryTypePriceId = Convert.ToInt32(request["Price"]);
            item.AgeOrderId = Convert.ToInt32(request["AgeOrder"]);
            item.CategoryTypeOrderId = Convert.ToInt32(request["CategoryTypeOrder"]);
            item.AuthorId = Convert.ToInt32(request["Author"]);
            return item;
        }

        private CategoryTypeViewModel UploadThumbnailImage(CategoryTypeViewModel model, HttpRequestBase request)
        {
            if (!request.Files.AllKeys.Any() || request.Files[0] == null) return model;

            var fileThumbnail = request.Files[0];
            var fileName = string.Empty;
            var uploadFilesDir = string.Format(@"{0}\thumbnailImage\{1}\{2}", AppConfig.UploadFolder, model.CategoryId, model.CategoryTypeId);
            if (!Directory.Exists(uploadFilesDir))
            {
                Directory.CreateDirectory(uploadFilesDir);
            }
            else
            {
                var folder = new DirectoryInfo(uploadFilesDir);
                foreach (var file in folder.GetFiles())
                {
                    if (string.IsNullOrEmpty(fileThumbnail.FileName))
                        fileName = file.Name;
                    else
                        file.Delete();
                }
            }
            var fileSavePath = Path.Combine(uploadFilesDir, !string.IsNullOrEmpty(fileThumbnail.FileName) ? fileThumbnail.FileName : fileName);
            if (!string.IsNullOrEmpty(fileThumbnail.FileName))
                fileThumbnail.SaveAs(fileSavePath);

            model.FileThumbnail = string.Format("{0}\\{1}", uploadFilesDir, !string.IsNullOrEmpty(fileThumbnail.FileName) ? fileThumbnail.FileName : fileName);
            return model;
        }
	}
}

GdsVideoBackend/Views/CategoryType/PatialView/_CategoryTypeParentDialog.cshtml
@model GdsVideoBackend.Models.CategoryTypeFromViewModel

<div id="add-new-category-type-parent" class="modal fade" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <h3 class="m-t-none m-b">Sign in</h3>
                        <form id="category-type-parent-form" role="form" action="@Url.Action("Insert", "CategoryType")" enctype="multipart/form-data">
                            <div class="form-group row">
                                <div class="col-sm-6">
                                    <label>Tên gói</label> <input name="CategoryTypeName" type="text" placeholder="Tên gói" class="category-type-name form-control">
                                </div>
                                <div class="col-sm-6">
                                    <label>Giá tiền</label>
                                    <select class="form-control m-b price" name="Price">
                                        @foreach (var item in Model.PriceSetting)
                                        {
                                            <option value="@item.Id" @(Model.PriceSetting.First() == item ? "selected='selected'" : "")>@item.Price</option>
                                        }
                                    </select>
                                </div>
                                <div class="col-sm-6">
                                    <label>Độ tuổi</label>
                                    <select class="form-control m-b age-order" name="AgeOrder">
                                        @foreach (var item in Model.AgeOrderSetting)
                                        {
                                            <option value="@item.Id" @(Model.AgeOrderSetting.First() == item ? "selected='selected'" : "")>@item.Name</option>
                                        }
                                    </select>
                                </div>
                                <div class="col-sm-6">
                                    <label>Thứ tự gói</label>
                                    <select class="form-control m-b categorytype-order" name="CategoryTypeOrder">
                                        <option value="0">-- Mắc định --</option>
                                        <option value="100">Thấp</option>
                                        <option value="200">Trung bình</option>
                                        <option value="300">Cao</option>
                                    </select>
                                </div>
                                <div class="col-sm-6">
                                    <label>Tên tác giả</label>
                                    <select class="form-control m-b author" name="Author">
                                        <option value="0">-- Chọn tác giả --</option>
                                        @foreach (var item in Model.AuthorSettings)
                                        {
                                            <option value="@item.Id">@item.Name</option>
                                        }
                                    </select>

                                </div>
                                <div class="col-sm-6">
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6">
                                    <div class="col-sm-8"><label>Ảnh đại diện</label></div>
                                    <div class="col-sm-4"><button id="replace-photo" class="btn btn-success btn-sm">Thêm ảnh</button></div>
                                    <input type="file" id="replace-photo-tag" style="display: none" name="FileThumbnail" accept="images/*">
                                </div>
                                <div class="col-sm-6">
                                    <img id="image-photo" src="" width="300" height="200" />
                                </div>
                            </div>
                            <div class="wrapper wrapper-content row">
                                <div class="col-lg-12">
                                    <div class="ibox float-e-margins">
                                        <div class="ibox-title" style="border: none;">
                                            <h5>Nội dung</h5>
                                            <button id="edit" class="btn btn-primary btn-xs m-l-sm" type="button">Edit</button>
                                            <button id="save" class="btn btn-primary btn-xs hidden" type="button">Save</button>
                                        </div>
                                        <div class="ibox-content no-padding">
                                            <div class="wrapper p-md cateogry-type-content">

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div>
                                <a id="save-parent" class="btn btn-sm btn-primary pull-right m-t-n-xs"><strong>Save</strong></a>
                            </div>
                            <input type="hidden" name="CategoryTypeId" class="category-type-id" value="0" />
                            <input type="hidden" name="CategoryId" class="category-id" value="0" />
                            <input type="hidden" name="Content" class="content" value="" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

GdsVideoBackend/Views/CategoryType/PatialView/_CategoryTypeParentTemplate.cshtml
<script id="categoryTypeParentTemplate" type="text/x-jquery-tmpl">
    <table class="table table-striped table-bordered table-hover dataTables-example dataTable dtr-inline" id="categoryTypeParent_Table" role="grid" aria-describedby="DataTables_Table_0_info">
        <thead>
            <tr role="row">
                <th class="sorting_asc" tabindex="0" aria-controls="categoryTypeParent_Table" rowspan="1" colspan="1" aria-sort="ascending" style="width: 189px;">Tên gói</th>
                <th class="sorting" tabindex="0" aria-controls="categoryTypeParent_Table" rowspan="1" colspan="1" style="width: 253px;">Độ tuổi</th>
                <th class="sorting" tabindex="0" aria-controls="categoryTypeParent_Table" rowspan="1" colspan="1" style="width: 253px;">Nội dung</th>
                <th class="sorting" tabindex="0" aria-controls="categoryTypeParent_Table" rowspan="1" colspan="1" style="width: 253px;">Tác giả</th>
                <th class="sorting" tabindex="0" aria-controls="categoryTypeParent_Table" rowspan="1" colspan="1" style="width: 229px;">Giá tiền</th>
                <th class="sorting" tabindex="0" aria-controls="categoryTypeParent_Table" rowspan="1" colspan="1" style="width: 162px;">Ngày tạo</th>
                <th tabindex="0" aria-controls="categoryTypeParent_Table" rowspan="1" colspan="1" style="width: 115px;"></th>
            </tr>
        </thead>
        <tbody>
            {{each Result}}
            <tr class="gradeA odd" role="row" id="${$value.CategoryTypeId}">
                <td class="category-type-name" data-filetype="${$value.MimeTypeImage}" data-file="${$value.ThumbnailImage}" data-childrenid="${$value.CategoryTypeId}">${$value.ChildrenName}</td>
                <td class="age" data-age="${$value.AgeOrderId}">${$value.AgeOrderName}</td>
                <td class="content-detail">{{html $value.Content}}</td>
                <td class="author" data-authorid="${$value.AuthorId}">${$value.AuthorName}</td>
                <td class="price" data-priceid="${$value.PriceId}">${$value.Price}</td>
                <td>${$value.DateTime}</td>
                <td>
                    <a class="btn btn-sm btn-default btn-rounded" href="categorydetail?categoryTypeId=${$value.CategoryTypeId}" target="_blank">Chi tiết</a>
                    <a class="btn btn-sm btn-success btn-rounded" onclick="bindingCategoryTypeDetail(this)" data-type="parent" data-categorytype-order="${$value.CategoryTpyeOrder}" data-id="${$value.CategoryTypeId}" data-toggle="modal" href="#add-new-category-type-parent">Edit</a>
                    <a class="btn btn-sm btn-danger btn-rounded" onclick="deleteCategoryType(this)" data-type="parent" data-id="${$value.CategoryTypeId}" href="#">Delete</a>
                </td>
            </tr>
            {{/each}}
        </tbody>
    </table>
</script>