GdsVideoBackend/Controllers/CategoryDetailController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gds.BusinessObject.TableModel;
using Gds.Setting;
using GdsVideoBackend.Domain;
using GdsVideoBackend.Models;
using System.Web.Script.Serialization;
using System.Collections.Generic;

namespace GdsVideoBackend.Controllers
{
    public class CategoryDetailController : Controller
    {
        private readonly ICategoryDetailService _categoryDetailService;
        private readonly ICategoryGroupService _categoryGroupService;

        public CategoryDetailController(ICategoryDetailService categoryDetailService, 
            ICategoryGroupService categoryGroupService)
        {
            _categoryDetailService = categoryDetailService;
            _categoryGroupService = categoryGroupService;
        }

        //
        // GET: /CategoryDetail/
        public ActionResult Index(int categoryTypeId)
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetCategoryGroup(int categoryTypeId)
        {
            var result = _categoryGroupService.GetCategoryGroups(categoryTypeId);
            return result.Any()
                ? Json(new { isSuccess = true, data = result })
                : Json(new { isSuccess = false });
        }

        [HttpPost]
        public ActionResult InsertCategoryGroup(CategoryTypeGroup model)
        {
            if (string.IsNullOrEmpty(model.CreateDateStr))
                model.CreatedDate = DateTime.UtcNow;
            else
                model.CreatedDate = Convert.ToDateTime(model.CreateDateStr);

            var result = _categoryGroupService.Insert(model);
            var modelResult = new List<CategoryGroupViewModel>()
            {
                new CategoryGroupViewModel
                {
                    CategoryGroupName = result.CategoryTypeGroupName,
                    CategoryGroupId = result.CategoryTypeGroupId,
                    CategoryDetails = new List<CategoryDetailModel>()
                }
            };
            return result != null
                ? Json(new { isSuccess = true, data = modelResult })
                : Json(new { isSuccess = false });
        }

        [HttpPost]
        public ActionResult UpdateCategoryGroup(CategoryTypeGroup model)
        {
            if (string.IsNullOrEmpty(model.CreateDateStr))
                model.CreatedDate = DateTime.UtcNow;
            else
                model.CreatedDate = Convert.ToDateTime(model.CreateDateStr);

            var result = _categoryGroupService.Update(model);
            var modelResult = new List<CategoryGroupViewModel>()
            {
                new CategoryGroupViewModel
                {
                    CategoryGroupName = result.CategoryTypeGroupName,
                    CategoryGroupId = result.CategoryTypeGroupId,
                }
            };
            return result != null
                ? Json(new { isSuccess = true, data = modelResult })
                : Json(new { isSuccess = false });
        }

        [HttpPost]
        public ActionResult DeleteCategoryGroup(int categoryGroupId)
        {
            return null;
        }

        [HttpPost]
        public ActionResult InsertUpateDetail()
        {
            var categoryGroupId = Request["CategoryGroupId"];
            var categoryTypeId = Request["CategoryTypeId"];
            var categoryDetailId = Request["CategoryDetailId"];
            var lectureIndex = Request["LectureIndex"];
            var categoryDetailName = Request["CategoryDetailName"];
            var model = new CategoryDetailModel
            {
                CategoryGroupId = Convert.ToInt32(categoryGroupId),
                CategoryTypeId = Convert.ToInt32(categoryTypeId),
                CategoryDetailName = categoryDetailName,
                LectureIndex = Convert.ToInt32(lectureIndex)
            };
            int cateDetailId;
            if (!int.TryParse(categoryDetailId, out cateDetailId))
            {
                cateDetailId = Insert(model);
            }
            else
            {
                model.CategoryDetailId = cateDetailId;
                cateDetailId = Update(model);
            }
            //Upload File
            model.CategoryDetailId = cateDetailId;
            UploadFile(model, Request);
            
            return Content("Uploaded Successfully");
        }

        [HttpPost]
        public JsonResult Delete(int categoryId)
        {
            var result = _categoryDetailService.Delete(categoryId);
            return result ? Json(new { isSuccess = true }) : Json(new { isSuccess = false });
        }

        private int InsertGroup(CategoryDetailModel model)
        {
            var result = _categoryDetailService.Insert(model);
            return result;
        }

        private int UpdateGroup(CategoryDetailModel model)
        {
            var result = _categoryDetailService.Update(model);
            return result;
        }

        private int Insert(CategoryDetailModel model)
        {
            var result = _categoryDetailService.Insert(model);
            return result;
        }

        private int Update(CategoryDetailModel model)
        {
            var result = _categoryDetailService.Update(model);
            return result;
        }

        private bool UploadFile(CategoryDetailModel model, HttpRequestBase request)
        {
            // UpFile
            var httpPostedFile = request.Files[0];
            if (httpPostedFile == null) return false;
            var categoryId = _categoryDetailService.GetCategoryId(Convert.ToInt32(model.CategoryTypeId));
            var uploadFilesDir = string.Format(@"{0}\{1}\{2}\{3}", AppConfig.UploadFolder, categoryId, model.CategoryTypeId, model.CategoryDetailId);
            if (!Directory.Exists(uploadFilesDir))
            {
                Directory.CreateDirectory(uploadFilesDir);
            }
            else
            {
                var folder = new DirectoryInfo(uploadFilesDir);
                foreach (var file in folder.GetFiles())
                {
                    file.Delete();
                }
            }
            var fileSavePath = Path.Combine(uploadFilesDir, httpPostedFile.FileName);
            httpPostedFile.SaveAs(fileSavePath);
            var fileModel = new PhysicalFiles
            {
                FileName = httpPostedFile.FileName,
                FileLength = httpPostedFile.ContentLength,
                FileServerNamePath = uploadFilesDir,
                CreatedDate = DateTime.UtcNow
            };
            _categoryDetailService.UpdateFileInfo(fileModel, model.CategoryDetailId);
            return true;
        }
    }
}

GdsVideoBackend/Views/CategoryDetail/Index.cshtml
@{
    ViewBag.Title = "CategoryDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section style
{
    <link href="~/Content/Style/dropzone.css" rel="stylesheet" />
}

@section left_menu
{
    @Html.Partial("~/Views/PartialViews/_LeftMenuPartial.cshtml")
}

<div class="col-lg-12">
    <div class="col-lg-12">
        <a  data-toggle="modal" class="btn btn-sm btn-primary" onclick="bindingCategoryTypoeGroupFrom(this, 'add')" href="#add-new-category-group">Thêm nhóm</a>
    </div>
    <div id="category_detail_Div">

    </div>
</div>

<div id="add-new-category-detail" class="modal fade" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <h3 class="m-t-none m-b">Thêm bài học</h3>
                        <form id="category-detail-form" class="row" role="form">
                            <div class="form-group col-sm-12">
                                <div class="col-sm-6">
                                    <label>Tên chủ đề</label> <input type="text" placeholder="Tên chủ đề" class="category-detail-name form-control">
                                </div>
                                <div class="col-sm-6">
                                    <label>Số thử tự</label> <input type="number" placeholder="Số thử tự" class="category-detail-index form-control">
                                </div>
                            </div>
                            <div class="form-group col-sm-12">
                                <div class="file-upload-container dropzone needsclick dz-clickable" style="display: none">
                                    <div class="dz-message needsclick">
                                        Drop files here or click to upload.<br>
                                        <span class="note needsclick">(This is just a demo dropzone. Selected files are <strong>not</strong> actually uploaded.)</span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-sm-12">
                                <a id="detail-save" class="btn btn-sm btn-primary pull-right m-t-n-xs"><strong>Save</strong></a>
                            </div>
                            <input type="hidden" id="category-detail-id" value="0" />
                            <input type="hidden" id="category-group-id" value="0" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="add-new-category-group" class="modal fade" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <h3 class="m-t-none m-b">Thêm nhóm</h3>
                        <form id="category-group-form" class="row" role="form">
                            <div class="form-group col-sm-12">
                                <div class="col-sm-6">
                                    <label>Tên nhóm</label> <input type="text" placeholder="Tên chủ đề" class="category-group-name form-control">
                                </div>
                                <div class="col-sm-6">
                                    <label>Số thử tự</label> <input type="number" placeholder="Số thử tự" class="category-group-index form-control">
                                </div>
                            </div>
                            <div class="form-group col-sm-12">
                                <a id="group-save" class="btn btn-sm btn-primary pull-right m-t-n-xs"><strong>Save</strong></a>
                            </div>
                            <input type="hidden" id="category-type-group-create-date" value="" />
                            <input type="hidden" id="category-type-group-id" value="0" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@Html.Partial("~/Views/CategoryDetail/PatialView/_CategoryTypeGroupPartial.cshtml")
@Html.Partial("~/Views/CategoryDetail/PatialView/_CategoryTypeGroupTemplate.cshtml")
@Html.Partial("~/Views/CategoryDetail/PatialView/_PhysicalFileTemplate.cshtml")
@*@Html.Partial("~/Views/CategoryDetail/PatialView/_CategoryDetailsTemplate.cshtml")*@

@section scripts{
    <script src="~/Scripts/jquery.tmpl.js"></script>
    <script src="~/Scripts/gds.categoryDetail.js"></script>
    <script type="text/javascript" src="~/Scripts/dropzone.js"></script>
    <script type="text/javascript">
        var setupDropzone = function setupDropzone() {
            if ($('.file-upload-container').length === 0) {
                return;
            }
            Dropzone.autoDiscover = false;
            var myDropzone = new Dropzone(".file-upload-container", {
                previewTemplate: document.querySelector('#preview-template').innerHTML,
                url: '@Url.Action("InsertUpateDetail", "CategoryDetail")',
                method: "POST",
                autoProcessQueue: false,
                clickable: ['.file-upload-container'],
                parallelUploads: 1,
                maxFilesize: 100, // in mb
                thumbnailWidth: 150,
                thumbnailHeight: 150,
                thumbnail: function(file, dataUrl) {
                    if (file.previewElement) {
                        $('#video-content').val(file);
                        file.previewElement.classList.remove("dz-file-preview");
                        var images = file.previewElement.querySelectorAll("[data-dz-thumbnail]");
                        for (var i = 0; i < images.length; i++) {
                            var thumbnailElement = images[i];
                            thumbnailElement.alt = file.name;
                            thumbnailElement.src = dataUrl;
                        }
                        setTimeout(function() { file.previewElement.classList.add("dz-image-preview"); }, 1);
                    }
                },
                queuecomplete: function () {
                    $('#save').show();
                    $('#add-new-category-detail').modal('hide');
                    bindingCategoryDetails();
                },
                sending: function(file, xhr, formData) {
                    formData.append('CategoryTypeId', parseInt(gds.getQueryVariable('categoryTypeId')));
                    var categoryDetailId = isNaN($("#category-detail-form #category-detail-id").val())
                        ? 0
                        : parseInt($("#category-detail-form #category-detail-id").val());
                    formData.append('CategoryDetailId', categoryDetailId);
                    formData.append('CategoryGroupId', $("#category-detail-form #category-group-id").val());
                    formData.append('LectureIndex', $("#category-detail-form .category-detail-index").val());
                    formData.append('CategoryDetailName', $("#category-detail-form .category-detail-name").val());
                }
            });

            $(document).on('click', '#detail-save', function (event) {
                $('#save').hide();
                myDropzone.processQueue();
            });
        };
        setupDropzone();
    </script>
}